server:
  port: 8902

logging:
  level:
    org.springframework.web: DEBUG
    com.netflix.discovery: 'OFF'
    com.org.wms: DEBUG
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8900/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/wo_mnagement/wms-config.git
          basedir: target/config
          username: arijitbairagya@yahoo.com
          password: XXXX
          clone-on-start: true
          default-label: master
  application:
    name: CONFIG_SERVER
