server:
  port: 8000
  servlet:
    context-path: ${wms.microservices.context.auth}

spring:
#  datasource:
#    url: jdbc:h2:mem:wms_oauth2
#    username: 
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
  application:
   name: AUTH_SERVER
  data:
    mongodb:
      uri: ${wms.microservices.database.auth}