server:
  port: 8901
  servlet:
    context-path: ${wms.microservices.context.wo-management}

spring:
  application:
    name: WO_MANAGEMENT
  data:
    mongodb:
      uri: ${wms.microservices.database.wo-management}
    
    